### ISSUE TITLE
Pointers unstable

### ISSUE THREAD

**Issue by AmarilloNL** [GapingWalrus/forkbot#1]
Hi there,

Been using the pointers for version 2.0.1. but testing it concludes that distribution is not fully working and the sysbot part works shortly but then it either doesn't search for the trade or it finds the trade but cancels it.

Hope you can help. If not I'll just patiently wait.

**Comment by GapingWalrus** [comment]
The issue is the portal pointer is unstable unfortunately till a new one is found nothing can be done

A short term fix would be to edit the trade routine to not read the portal offset and just assume its in portal but that could also result in it going to the wrong menus

**Comment by AmarilloNL** [comment]
I understand. Thank you for your response so far. I'll patiently wait for future updates.
